---
- hosts: all

  vars:
    current_user: "{{ ansible_user_id }}"

  pre_tasks:

    - name: Install SSH server
      apt: pkg=openssh-server
      become: yes

    - name: Install sshpass
      apt: pkg=sshpass
      become: yes

    - name: Disable SSHD startup
      shell: update-rc.d ssh disable
      become: yes

    - name: Create Installs directories
      file: path=~/Installs state=directory

    - name: Symlink ~/Installs
      file: src=~/Installs dest=/tmp/Installs state=link

    - name: Install apt-transport-https
      apt: pkg=apt-transport-https
      become: yes

    - name: Install pip
      apt: pkg=python3-pip
      become: yes

    - name: Upgrade pip
      pip: name=pip extra_args=--upgrade executable=pip3
      become: yes

    - name: setup python2 alternative
      alternatives:
        name: python
        path: /usr/bin/python2
        link: /usr/bin/python
        priority: 1
      become: yes

    - name: setup python3 alternative
      alternatives:
        name: python
        path: /usr/bin/python3
        link: /usr/bin/python
        priority: 2
      become: yes

    - name: Add pip3 as pip to .bash_profile
      lineinfile: dest=~/.bashrc line='alias pip=/usr/bin/pip3'

    - name: Install unzip
      apt: pkg=unzip
      become: yes

  roles:
    - source-control
    - vim
    - system
    - security
    - monitoring
    - configuration-management
    - media
    - clojure
    - nodejs
    - ruby
    - internet
    - office
    - nvidia
    - docker
    - docker-compose

  post_tasks:

    - name: Add docker group for user
      user: name={{ current_user }} groups=docker append=yes
      become: yes
