- name: Install nodejs
  apt: pkg=nodejs,npm state=latest
  become: yes

- name: Install Electron Packager
  npm: name=electron-packager version=14.0.4 global=yes
  become: yes

- name: Install vim plugins
  git: repo=https://github.com/pangloss/vim-javascript.git dest=~/.vim/bundle/vim-javascript
