- name: Install OpenVPN
  apt: pkg=openvpn
  become: yes

- name: Install chromium web browser
  apt: pkg=chromium
  become: yes

- name: Add google apt key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub
  become: yes

- name: Add google apt repository
  apt_repository: repo='deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' filename=google-chrome update_cache=yes
  become: yes

- name: Install chrome web browser
  apt: pkg=google-chrome-stable
  become: yes

- name: Download franz .deb
  get_url: url=https://github.com/meetfranz/franz/releases/download/v5.2.0/franz_5.2.0_amd64.deb dest=~/Installs/franz_5.2.0_amd64.deb
  register: get_url_result
  until: get_url_result | succeeded
  retries: 3
  delay: 1

- name: Install franz
  apt: deb=/tmp/Installs/franz_5.2.0_amd64.deb
  become: yes

- name: Install Deluge BitTorrent client
  apt: pkg={{ item }}
  with_items:
  - deluge
  - deluged
  - deluge-console
  become: yes

- name: Install postman installer/updater
  npm: name=postman-updater-linux version=0.0.2 global=yes
  become: yes

- name: Check if postman installed
  command: postman-updater check
  register: postman_installed

- name: Install postman
  command: postman-updater install
  when: postman_installed.stdout == 'No local installation of Postman found!'
  become: yes

- name: Create symlink for Postman executable
  file: src=/opt/postman/Postman dest=/usr/bin/postman state=link
  become: yes

- name: Install uGet download manager
  apt: pkg=uget
  become: yes
