- name: Install required packages
  apt: name=python3-pip,software-properties-common update_cache=yes
  become: yes

- name: Upgrade pip
  pip: name=pip state=latest extra_args=--upgrade executable=pip3
  become: yes

- name: Install setuptools
  pip: name=setuptools state=latest executable=pip3
  become: yes

- name: Install docker-compose
  pip: name=docker-compose executable=pip3
  become: yes
