- name: Install VLC media player
  apt: pkg=vlc
  become: yes

- name: Add spotify apt key
  apt_key: url=https://download.spotify.com/debian/pubkey_0D811D58.gpg
  become: yes

- name: Add spotify repository
  apt_repository: repo="deb http://repository.spotify.com stable non-free"
  become: yes

- name: Install spotify client
  apt: pkg=spotify-client update_cache=yes
  become: yes

- name: Install GIMP photo editor
  apt: pkg=gimp
  become: yes

- name: Install handbrake video converter
  apt: pkg=handbrake
  become: yes

- name: Download Auryo .deb
  get_url: url=https://github.com/Superjo149/auryo/releases/download/v1.4.3/Auryo_1.4.3_amd64.deb dest=~/Installs/Auryo_1.4.3_amd64.deb

- name: Install Auryo
  apt: deb=/tmp/Installs/Auryo_1.4.3_amd64.deb
  become: yes

- name: Install spotify downloader
  pip: name=spotdl executable=pip3
  become: yes

- name: Install audible player
  snap: name=audible-for-linux
  become: yes
