- name: Install vim
  apt: pkg=vim,vim-nox,vim-addon-manager
  become: yes

- name: Install vim plugin packages
  apt: pkg=vim-{{ item }}
  with_items: "{{ vim_plugin_package }}"
  become: yes

- name: Install vim plugins
  command: vam install {{ item }}
  with_items: "{{ vim_plugin_package }}"

- name: Setup paths for vim
  file: path={{ item }} state=directory
  with_items:
  - ~/.vim/autoload
  - ~/.vim/bundle

- name: Install vim plugin
  git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.name }}
  with_items:
  - {repo: "https://github.com/scrooloose/nerdtree.git", name: nerdtree}
  - {repo: "https://github.com/Xuyuanp/nerdtree-git-plugin.git", name: nerdtree-git-plugin}
  - {repo: "https://github.com/ntpeters/vim-better-whitespace.git", name: vim-better-whitespace}
  - {repo: "https://github.com/airblade/vim-gitgutter.git", name: vim-gitgutter}
  - {repo: "https://github.com/plasticboy/vim-markdown.git", name: vim-markdown}
  - {repo: "https://github.com/IN3D/vim-raml.git", name: vim-raml}
  - {repo: "https://github.com/aklt/plantuml-syntax.git", name: plantuml-syntax}

- name: Update .vimrc
  lineinfile: dest=~/.vimrc line={{ item }} create=yes
  with_items:
  - execute pathogen#infect()
  - syntax on
  - filetype plugin indent on
  - :set tabstop=2
  - :set shiftwidth=2
  - :set expandtab
  - :set nobackup
  - :set noswapfile
  - let g:vim_markdown_folding_style_pythonic = 1
  - map <C-n> :NERDTreeToggle<CR>
  - autocmd BufEnter * EnableStripWhitespaceOnSave

- name: Set vim as git editor
  git_config: name=core.editor scope=global value=vim
